Revert "MB-17118: cluster_run finds pluggable-ui config files"
breaks cluster_run

couchbasesMBP3:ns_server artem$ ./cluster_run -n 1
Traceback (most recent call last):
  File "./cluster_run", line 364, in <module>
    main()
  File "./cluster_run", line 349, in main
    for file in os.listdir(plugins_dir):
OSError: [Errno 2] No such file or directory: '../build/cluster_run_ui_plugins'
This reverts commit a6f1a616049f94520de404c69e057ea944e7dc10.

Change-Id: I7aa0add670932c07b7e3ef26a7958d1979c20753
Reviewed-on: http://review.couchbase.org/57977
Reviewed-by: Artem Stemkovski <artem@couchbase.com>
Tested-by: Artem Stemkovski <artem@couchbase.com>