Added workaround to build with gccgo 4.7.3
gccgo 4.7.3 emits an error that we don't return a value
from the function causing the build to fail without the
following explicit return.

vbmap.go:43:1: error: control reaches end of non-void function

Change-Id: I50d1ac27b93de9d553a56830bd61c00d436c61fa
Reviewed-on: http://review.couchbase.org/31383
Reviewed-by: Aliaksey Artamonau <aliaksiej.artamonau@gmail.com>
Tested-by: Aliaksey Artamonau <aliaksiej.artamonau@gmail.com>