MB-10160 cluster_run crashes with custom libpng
Extending the DYLD_LIBRARY_PATH to include /usr/local/lib caused the OSX
to load any library installed in /usr/local/lib to take precedence over
the normal search for libs in the path, since those do not necessary
match the library which the software was build against it causes the
startup to fail with errors like

    dyld: Symbol not found: __cg_png_create_info_struct

/usr/local/lib is included in the default search path for libraries via
DYLD_FALLBACK_LIBRARY_PATH

Change-Id: Ia65173f712ef266f8b5ddd3547916ae499469bf2
Reviewed-on: http://review.couchbase.org/33336
Reviewed-by: Sriram Melkote <siri@couchbase.com>
Tested-by: Sriram Melkote <siri@couchbase.com>